package clasesHibernate;
// Generated 4 feb 2025 10:27:30 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Deportes generated by hbm2java
 */
public class Deportes implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set equiposes = new HashSet(0);

	public Deportes() {
	}

	public Deportes(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public Deportes(String nombre, Set equiposes) {
		this.nombre = nombre;
		this.equiposes = equiposes;
	}

	public Deportes(int id, String nombre, Set equiposes) {
		this.id = id;
		this.nombre = nombre;
		this.equiposes = equiposes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getEquiposes() {
		return this.equiposes;
	}

	public void setEquiposes(Set equiposes) {
		this.equiposes = equiposes;
	}

	@Override
	public String toString() {
		return "Deportes [id=" + id + ", nombre=" + nombre + "]";
	}

}
